[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Prevent browsers from incorrectly detecting non-scripts as scripts
    X-Content-Type-Options: nosniff
